### PR TITLE
Range

### PR DESCRIPTION
**Pull request by esheldon**

### CODE REVIEW

**Comment by esheldon** [comment]
closes #155

**Review by beckermr — CHANGES_REQUESTED** [review]
The duplication of the integration test code is too much debt. Let's ship a simple smoke test that runs the code with the range keyword and makes sure it doesn't fail.

**Comment by esheldon** [comment]
How do we do that without duplicating that stuff for the sim? Or do you mean do the same sim but just have a very small smoke test on top of it making sure it doesn't crash?

**Comment by beckermr** [comment]
> Or do you mean do the same sim but just have a very small smoke test on top of it making sure it doesn't crash?

Yup. We should be able to define an additional test in the orignal test file that calls the code differently and makes sure it completes.

**Comment by esheldon** [comment]
I don't know what you mean

**Comment by beckermr** [comment]
Can I push to this branch? Might be easier for me to write it down.

**Comment by esheldon** [comment]
sure

**Comment by esheldon** [comment]
good with me

**Pull request merged**
