### PR TITLE
ENH coadd with pixel scales

### PR DESCRIPTION
**Pull request by beckermr**
This PR adds coadding in surface brightness units.

### CODE REVIEW

**Comment by beckermr** [comment]
@esheldon this one is ready for a review

**Comment by esheldon** [comment]
I'll go through it today.

Can you please give a few sentences explaining why you would like to work in surface brightness?  What is the motivation?

**Comment by beckermr** [comment]
Right now we are averaging fluxes over regions of the ccd that subtend different areas of the source when we do the interpolation before coadding. We need to work in a fully intrinsic quantity when interpolating.

**Comment by esheldon** [comment]
We will need to make sure we put these back on the right zero point after the coadd.

**Comment by beckermr** [comment]
I am not sure what you mean. Do we have pixel area factors in the zero points?

**Comment by esheldon** [comment]
If you divide by pixel scale squared you have changed the zero point.  We need to make sure we end up on zp 30 when all is said and done.

**Comment by esheldon** [comment]
The images we read from disk are not in SB units

**Comment by beckermr** [comment]
> The images we read from disk are not in SB units

Right. This is the point.

**Comment by beckermr** [comment]
> If you divide by pixel scale squared you have changed the zero point. We need to make sure we end up on zp 30 when all is said and done.

In this PR I divide by the pixel area for each SE image, interp to coadd, and then multiply by the coadd pixel area. I don't think this procedure preserves the zero points exactly, but it has to be close.

**Comment by esheldon** [comment]
OK, I think I understand and this sounds good. I'll give it a look

**Comment by esheldon** [comment]
should we have a test where we have an expected image for the coadd, and we input a few SE images with quite different pixel scales and make sure it matches?

**Comment by beckermr** [comment]
> should we have a test where we have an expected image for the coadd, and we input a few SE images with quite different pixel scales and make sure it matches?

Yes this is a good idea. The test cases we have don't quite cover this case. 

FWIW the pixel area variations in the data are fractions of a percent typically.

**Comment by beckermr** [comment]
Ahhh. I can add pixel scale variation here: https://github.com/beckermr/pizza-cutter/blob/master/pizza_cutter/des_pizza_cutter/integration_test/data.py#L131

**Comment by beckermr** [comment]
So right now we get this with a relatively large object compared to the pixel scale:

```
max abs diff: 0.00046239438
fwhm true|coadd: 1.8027756377319946|1.8027756377319946
xcen true|coadd: 24.000000254829413|24.087043069272738
ycen true|coadd: 24.00000025482941|24.089575641934758
e1 true|coadd: -6.712835103966041e-16|0.000131838460220024
e2 true|coadd: 0.7572253942489624|0.7558943629264832
```

**Comment by beckermr** [comment]
This is within spitting distance of the accuracy of the stack coadding and my simpler code. The center offset is odd and I am looking into that now.

**Comment by beckermr** [comment]
dropped a lot when turning down the noise in the images to zero

```
max abs diff: 0.0003316853
fwhm true|coadd: 2.078533659771992|2.0791606425468734
xcen true|coadd: 24.0000002934593|24.013558107618042
ycen true|coadd: 24.000000293459305|23.990612578632472
e1 true|coadd: -6.318946254647068e-16|-0.0009090215316973628
e2 true|coadd: 0.769792079925537|0.763965904712677
```

**Comment by beckermr** [comment]
I'm happy with these tests.

**Comment by esheldon** [comment]
LGTM

**Pull request merged**
