### PR TITLE
expandvars in paths as needed, save in meds files

### LINKED ISSUE #116: Use env vars in paths for the info file and meds files, expand when using

### PR DESCRIPTION
**Pull request by esheldon**
closes #116

### CODE REVIEW

**Comment by esheldon** [comment]
relies on a recent fix in fitsio so that expandvars is used in read_header (a recent regression)

**Comment by esheldon** [comment]
also not that the env vars will only be present in the info if using a recent desmeds

**Comment by beckermr** [comment]
I didn't follow the last comment on desmeds. Can we simply add the MEDS_DIR and DESDATA to the metadata extension.

**Comment by esheldon** [comment]
this code will work in any case.  But I was just noting that the info created by desmeds in the past had the vars expanded but I changed this.

**Comment by esheldon** [comment]
also I would rather avoid doing the "replace paths with $MEDS_DIR" stuff, I find it messy.  Instead let's rely on desmeds to use the appropriate environment vars

**Pull request merged**
