### PR TITLE
ENH code for coadding

### PR DESCRIPTION
**Pull request by beckermr**
This PR has the base code for coadding. I need to add more docs and some tests, but it works OK.

### CODE REVIEW

**Comment by beckermr** [comment]
@esheldon @rmjarvis for viz

**Comment by esheldon** [comment]
We are definitely going to want to cut epochs with masking like that.  What is the bit?

**Comment by beckermr** [comment]
Do you mean the big vertical stripes? 

Stupid me lost which slice I was working on so I can't go back and check. I'll find it.

**Comment by esheldon** [comment]
My guess is we won't be able to just remove those chunks, will rather have to check for a large fractioni of the area being masked.  But I'm still curious what is the bit there.

In fact for this case, where the regions are rectangular, I wonder if we should taylor the cells around these masks.

**Comment by beckermr** [comment]
Found it. This is 2**6 = 64, or TRAIL.

**Comment by beckermr** [comment]
K. I added this to the list of flags for singe epochs that we simply cut.

**Comment by esheldon** [comment]
we can probably deal with it in a more clever way, but maybe punt for now

**Comment by beckermr** [comment]
Alright, I am going to merge this PR. The DES coadding code needs tests, but I am punting on this until we actually want to start using it.

**Pull request merged**
