### PR TITLE
check for cases without any image available

### LINKED ISSUE #125: deal with None observations returned when running metadetect
and understand why they are coming back None in this case; seems that should not happen for these large patches

### PR DESCRIPTION
**Pull request by esheldon**
closes #125 

turns out the issue wasn't None for the mbobs, but lenght zero ObsList i

### CODE REVIEW

**Comment by beckermr** [comment]
Ack. I just hacked in a fix for this too in another PR. Let's merge this one and then I can resolve the conflicts.

**Comment by beckermr** [comment]
Good to merge?

**Comment by esheldon** [comment]
I guess we should start assigning these issues ASAP

**Comment by esheldon** [comment]
was your solution equivalent to mine?

**Comment by beckermr** [comment]
Yup but yours is better.

**Pull request merged**
