### PR TITLE
use tuples for shapes so we can hash them

### LINKED ISSUE #141: error with cacheing
this is probably related to changing image shapes to list from tuple in the info file

```
INFO:pizza_cutter.des_pizza_cutter._pizza_cutter:reserving mosaic images...
|--------------------| 0/1521   0% [elapsed: 00:00 left: ?]INFO:pizza_cutter.des_pizza_cutter._pizza_cutter:processing object 0
Traceback (most recent call last):
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/bin/des-pizza-cutter", line 4, in <module>
    __import__('pkg_resources').run_script('pizza-cutter==0.1.0', 'des-pizza-cutter')
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1451, in run_script
    exec(script_code, namespace, namespace)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/EGG-INFO/scripts/des-pizza-cutter", line 87, in <module>
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/EGG-INFO/scripts/des-pizza-cutter", line 83, in main
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/pizza_cutter/des_pizza_cutter/_pizza_cutter.py", line 147, in make_des_pizza_slices
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/pizza_cutter/des_pizza_cutter/_pizza_cutter.py", line 283, in _coadd_and_write_images
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/pizza_cutter/des_pizza_cutter/_coadd_slices.py", line 424, in _coadd_slice_inputs
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/pizza_cutter/des_pizza_cutter/_se_image.py", line 798, in resample
TypeError: unhashable type: 'list'
tilename: DES0039-3914
```

### PR DESCRIPTION
**Pull request by esheldon**
closes #141

### CODE REVIEW

**Comment by beckermr** [comment]
We should not do this here, but instead when read the info back in during the load step. The issues is the pyyaml does weird shit when you cache tuples.

**Comment by beckermr** [comment]
Here is an example

```
In [12]: print(yaml.dump((10, 11)))                                                                                                                                                                     
!!python/tuple
- 10
- 11


In [13]: print(yaml.dump([10, 11]))                                                                                                                                                                     
- 10
- 11


```

**Comment by esheldon** [comment]
Yeah, but it works from python and we will only ever read them from python

**Comment by beckermr** [comment]
it also does this (which I found in the info files too)

```
In [15]: t = (10, 11)                                                                                                                                                                                   

In [16]: print(yaml.dump({'a': t, 'b': t}))                                                                                                                                                             
a: &id001 !!python/tuple
- 10
- 11
b: *id001
```

The anchor is annoying.

**Comment by beckermr** [comment]
We can add a simple check to convert them to tuples in the load function. Also, this will be more robust since it will handle info files from more than one source, including the sims.

**Comment by beckermr** [comment]
I'm going to merge this PR, removing the tuples. We can default to larger caches for now.

**Pull request merged**
