### PR TITLE
use desmeds classes to query information about the coadd and sources

### LINKED ISSUE #30: use desmeds for file info
The file info classes are in desmeds and we should just pull them from there.

https://github.com/esheldon/desmeds

### PR DESCRIPTION
**Pull request by esheldon**
closes #30

### CODE REVIEW

**Comment by beckermr** [comment]
you will need to install desmeds in the CI. I can help with this, but simply adding it to the requirements.txt file should do the trick.

**Comment by esheldon** [comment]
Is there a way to make it known that this is an optional dependency?

**Comment by beckermr** [comment]
flake8 is a cruel but benevolent master

**Comment by beckermr** [comment]
also https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

**Comment by beckermr** [comment]
but TBH i'd just list it, this is a DES only code anyways

**Pull request merged**
