### PR TITLE
PERF speed up single lanczos func

### LINKED ISSUE #128: remove min,max calls from lanczos_resample
This should make that function a lot faster.

### PR DESCRIPTION
**Pull request by beckermr**
Closes #128

### CODE REVIEW

**Comment by esheldon** [comment]
do you still want to zero out pixels with edge set?

**Comment by beckermr** [comment]
I don't think so. The values returned by lanczos_resample are zeroed already. And then for the PSF we want zeros there so we already have them.

**Comment by beckermr** [comment]
actually - filling with zero is better

**Comment by esheldon** [comment]
they are not totally zerod.   The way it works now it uses an incomplete kernel for these

**Pull request merged**
