### PR TITLE
REF use the approximate inversion interpolator to avoid scamp polynomial evals

### LINKED ISSUE #89: Apply2DPolynomial is bottleneck for scamp
probably should cache it

### PR DESCRIPTION
**Pull request by beckermr**
This PR attempts to use the approximate WCs inversion interpolator to avoid a bottleneck from evaluating 2d polynomials in python. 

closes #89 

@esheldon Can you redo your Y5 test with this branch?

### CODE REVIEW

**Comment by esheldon** [comment]
running now

**Comment by esheldon** [comment]
something is going wrong here, it is spending all its time reading headers
```
   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     1561  233.598    0.150  277.405    0.178 fitslib.py:120(read_header)
     1560   40.017    0.026   40.017    0.026 {method 'read_header' of '_fitsio.FITS' objects}
        6   31.167    5.195   31.167    5.195 {method 'create_image_hdu' of '_fitsio.FITS' objects}
       30   25.468    0.849   25.468    0.849 _lanczos.py:77(lanczos_resample_two)
       60   20.363    0.339   20.562    0.343 _wcs_utils.py:55(__call__)
        5   19.225    3.845   19.293    3.859 _wcs_utils.py:50(__init__)
     8358   11.765    0.001   11.918    0.001 wcsutil.py:1177(Apply2DPolynomial)
     1941   11.103    0.006   11.103    0.006 {method 'read' of '_io.FileIO' objects}
       20    5.607    0.280    5.607    0.280 {method 'read_image' of '_fitsio.FITS' objects}

```

**Comment by beckermr** [comment]
UGH what?

**Comment by beckermr** [comment]
is it blocked or running?

**Comment by esheldon** [comment]
It is running but its spending all its time reading headers

**Comment by esheldon** [comment]
this appears to be the file system

**Comment by esheldon** [comment]
OK, I spoke to soon. Running with the `preptile` branch is fast, so it isn't the file system.

**Comment by esheldon** [comment]
this was a problem of the cache size being too small.

For DES we can set the image size without reading the header, I'll do that.

**Comment by beckermr** [comment]
Ack. I squashed the commits on master, which is why the preptile stuff appears again.

**Comment by esheldon** [comment]
I merged preptile myself so I could update the info with the newer code

**Comment by esheldon** [comment]
did I mess up?

**Comment by beckermr** [comment]
nah. github is smart.

**Comment by esheldon** [comment]
git is smart :)

**Comment by esheldon** [comment]
current profile below. We are hitting read_image now for the same cache size reasons
```
   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      193  163.560    0.847  163.560    0.847 _lanczos.py:77(lanczos_resample_two)
      387  105.552    0.273  106.666    0.276 _wcs_utils.py:55(__call__)
      360   73.895    0.205   73.895    0.205 {method 'read_image' of '_fitsio.FITS' objects}
       21   73.804    3.514   74.106    3.529 _wcs_utils.py:50(__init__)
        6   34.572    5.762   34.572    5.762 {method 'create_image_hdu' of '_fitsio.FITS' objects}
      382   29.187    0.076   33.420    0.087 interpolate.py:105(_grid_interp)
      167   27.793    0.166   32.554    0.195 fitslib.py:120(read_header)
    45994   20.932    0.000   21.438    0.000 wcsutil.py:1177(Apply2DPolynomial)
      136    9.617    0.071    9.617    0.071 {method 'normal' of 'mtrand.RandomState' objects}
     1941    8.533    0.004    8.533    0.004 {method 'read' of '_io.FileIO' objects}

```

**Comment by beckermr** [comment]
Wait the point of this PR was to fix the calls to Apply2DPolynomial. Those look better, right?

**Comment by esheldon** [comment]
yeah, the dominant wcs related thing is now in the `__call__` method of the `WCSInversionInterpolator` rather than in `Apply2DPolynomial`.  So we can probably merge.

But the above profile shows that, for cases where there are lots of epochs going into the coadd, we can see significant contribution from image reading.

**Comment by beckermr** [comment]
Ahhh ok. Cool.

We can move to opening FITS objects in another PR. As long as we keep them open between slices, cfitsio should do some caching for us. However, IDK how many open files we can keep around, so we may want to cache the FITS objects as well. Unfortunately, the python caching functions don't supply callbacks for things with side effects. We would need a call back to close the FITS object when it gets evicted from the cache. 

There is a package that enables this:

https://stackoverflow.com/questions/29470958/python-functools-lru-cache-eviction-callback-or-equivalent

**Comment by esheldon** [comment]
although, should we be more agressively cacheing these `WCSInversionInterpolator` ?

**Comment by beckermr** [comment]
You saw memory issues when doing this. I think each one is pretty hefty since it is storing 2 4096x2048 grids.

**Pull request merged**
